### ISSUE TITLE
proxy returns 4 items and still tfrobot says couldn't find resources

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-go#1035]
https://gridproxy.dev.grid.tf/nodes?page=1&size=20&ret_count=true&status=up&free_mru=17179869184&free_sru=54760833024&sort_by=free_cru&sort_order=desc&healthy=true

```yml
node_groups:
  - name: group_a
    nodes_count: 3
    free_cpu: 2
    free_mru: 16
    free_ssd: 50
vms:
  - name: examplevm123
    vms_count: 3
    node_group: group_a
    cpu: 1
    mem: 0.25
    public_ip4: false
    public_ip6: false
    ssd:
      - size: 15
        mount_point: /mnt/ssd
    flist: https://hub.grid.tf/tf-official-apps/base:latest.flist
    entry_point: /sbin/zinit init
    root_size: 0
    ssh_key: example1
    env_vars:
      user: user1
      pwd: 1234
ssh_keys:
  example1: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDYNeJXJV2FNEwuQz6e0jkKeqRbKWwftBKq+sjSTqa2x
mnemonic: 
network: dev
max_retries: 5

```
