### ISSUE TITLE
🐞 [Bug]: latest tfrobot node filter is broken

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/tfgrid-sdk-go#1036]
### What happened?

tested but always the same result:
- last 5 tfrobot versions
- towards all nets
- with different configs
- with different mnemonics

[mainnet output.log](https://github.com/threefoldtech/tfgrid-sdk-go/files/15435281/output.log)

example config (did not find any config that works):
```
node_groups:
  - name: group_a
    nodes_count: 3
    free_cpu: 2
    free_mru: 16
    free_ssd: 50
vms:
  - name: examplevm123
    vms_count: 3
    node_group: group_a
    cpu: 1
    mem: 0.25
    public_ip4: false
    public_ip6: false
    ssd:
      - size: 15
        mount_point: /mnt/ssd
    flist: https://hub.grid.tf/tf-official-apps/base:latest.flist
    entry_point: /sbin/zinit init
    root_size: 0
    ssh_key: example1
    env_vars:
      user: user1
      pwd: 1234
ssh_keys:
  example1: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDYNeJXJV2FNEwuQz6e0jkKeqRbKWwftBKq+sjSTqa2x
mnemonic: <removed>
network: main
max_retries: 5
```

another:
```
node_groups:
  - name: group_a
    nodes_count: 3
    free_cpu: 2
    free_mru: 8
    free_ssd: 50
    free_hdd: 0
    dedicated: false
    public_ip4: false
    public_ip6: false
    certified: false
    region: europe
vms:
  - name: examplevm123
    vms_count: 2
    node_group: group_a
    cpu: 1
    mem: 0.25
    public_ip4: false
    public_ip6: false
    ssd:
      - size: 15
        mount_point: /mnt/ssd
    flist: https://hub.grid.tf/tf-official-apps/base:latest.flist
    entry_point: /sbin/zinit init
    root_size: 0
    ssh_key: example1
    env_vars:
      user: user1
      pwd: 1234
ssh_keys:
  example1: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDYNeJXJV2FNEwuQz6e0jkKeqRbKWwftBKq+sjSTqa2x
mnemonic: <removed>
network: main
max_retries: 5
```

always results in
```
3:46PM DBG failed to deploy error="could not find enough nodes with options: healthy: true, status: up, free_mru: 17179869184, free_sru: 53687091200, total_cru: 2, available_for: 604" Node group=group_a
3:46PM INF Retrying to deploy Deployment trial=2 Node group=group_a
3:46PM INF Filter nodes Node group=group_a
3:46PM DBG failed to deploy error="could not find enough nodes with options: available_for: 604, healthy: true, status: up, free_mru: 17179869184, free_sru: 53687091200, total_cru: 2" Node group=group_a
3:46PM INF Retrying to deploy Deployment trial=3 Node group=group_a
3:46PM INF Filter nodes Node group=group_a
3:46PM DBG failed to deploy error="could not find enough nodes with options: total_cru: 2, available_for: 604, healthy: true, status: up, free_mru: 17179869184, free_sru: 53687091200" Node group=group_a
3:46PM INF Retrying to deploy Deployment trial=4 Node group=group_a
3:46PM INF Filter nodes Node group=group_a
3:46PM DBG failed to deploy error="could not find enough nodes with options: healthy: true, status: up, free_mru: 17179869184, free_sru: 53687091200, total_cru: 2, available_for: 604" Node group=group_a
3:46PM INF Retrying to deploy Deployment trial=5 Node group=group_a
3:46PM INF Filter nodes Node group=group_a
3:46PM DBG failed to deploy error="could not find enough nodes with options: total_cru: 2, available_for: 604, healthy: true, status: up, free_mru: 17179869184, free_sru: 53687091200" Node group=group_a
3:46PM INF Retrying to deploy Deployment trial=6 Node group=group_a
3:46PM INF Filter nodes Node group=group_a
3:46PM DBG failed to deploy error="could not find enough nodes with options: status: up, free_mru: 17179869184, free_sru: 53687091200, total_cru: 2, available_for: 604, healthy: true" Node group=group_a
3:46PM INF canceling contracts project name=vm/group_a
ok: {}
error:
    group_a: 'could not find enough nodes with options: status: up, free_mru: 17179869184, free_sru: 53687091200, total_cru: 2, available_for: 604, healthy: true'

3:46PM INF Deployment took 4m54.169127894s
```

### which network/s did you face the problem on?

Dev, QA, Test, Main

### Twin ID/s

604

### Version

v0.15.4

### Relevant log output

```console
3:46PM INF project is canceled project name=vm/group_a
ok: {}
error:
    group_a: 'could not find enough nodes with options: status: up, free_mru: 17179869184, free_sru: 53687091200, total_cru: 2, available_for: 604, healthy: true'
```
