### ISSUE TITLE
mycelium integration in zos grid go client

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/tfgrid-sdk-go#677]
### Is your feature request related to a problem? Please describe

Right now, we are adding support for mycelium in zos. this will require some changes to the go client to support this new feature. 

ZOS consider mycelium as an optional feature, which means older clients can still work but not be able to use this feature without breaking.

### Describe the solution you'd like

The mycelium feature is used in 2 parts:
- It has to be configured in the network itself as defined [here](https://github.com/threefoldtech/zos/blob/31e4a52be469ed109d5c6f60bd67518d0ef9783a/pkg/gridtypes/zos/network.go#L87) 
- This setup if provided enable mycelium for this network on this node. The seed provided has to be unique and valid. Has to be 32 bytes and encoded as hex in the json body. 
- Once the network mycelium was set up. We can now enable it per VM that is part of this network as [here](https://github.com/threefoldtech/zos/blob/31e4a52be469ed109d5c6f60bd67518d0ef9783a/pkg/gridtypes/zos/zmachine.go#L59)

**Comment by Eslam-Nawara** [comment]
Verified: 
tried deploying vm with random mycelium ip seed on a network with random mycelium key and returned mycelium ip successfully and was able to connect the vm using mycelium ip.
```yaml
➜  test-go go run *.go
2024/03/03 16:27:16 mnemonics: ***
2024/03/03 16:27:16 network: dev
4:27PM INF starting peer session=tf-76091 twin=4653
name: vm
flist: https://hub.grid.tf/tf-official-apps/base:latest.flist
flistchecksum: ""
publicip: false
publicip6: false
planetary: false
corex: false
computedip: ""
computedip6: ""
planetaryip: ""
myceliumip: 5f6:bb70:c17:1c50:ff0f:b143:e764:3009
ip: 10.20.2.2
myceliumipseed:
    - 177
    - 67
    - 231
    - 100
    - 48
    - 9
description: ""
gpus: []
cpu: 2
memory: 1024
rootfssize: 0
entrypoint: /sbin/zinit init
mounts: []
zlogs: []
envvars:
    SSH_KEY: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCjGsz8evMP5F4jh3FI9cAJb1HxXtwObR+Yqz/1HPDXHL8El9fDsfpiKjLvfvb3LesMPeo4Sttda+u/ytaOM8aIU6p45dSDqphkDdplWZGk4iz+KGO/1UyvVhF09oiFbYh8qAm2eWUal6cufDtCnisDz3RDNpjK1uSmcQ/hdWiTWi2wRgBx8TseZDCDzuD14rPKaPlJg7I6NIhGaxRaN39ti6FsW3udi3eIA4VYl8QBswwLf0o3JLAwCPgOyH63Hc5WEE6e9ofP9b1cw6ZUwLuuINWWWysLo9/WHMbVWDuQEOybxz6qJHgZ8KVURh2GQqSxeZyCxZGOJlrNgt4sKdI8Hgs5hodZabp1SZUbpOnH5ujzD7KahwUhF/+EZPd8/+FouKsWsnkrM+g6q6rOHtdBZ0QEwDpXy6I6PVEkRaNNtnmEme+IsJBLgcmRms7h8xzjj0touV674xPiNu393uXvu9qtoxtZlYdeeh4VtaX+4xVsxXu20HGgGWEzilEJTik= eslam@eslam-Inspiron-3576 '
networkname: vmTestingNetwork
consoleurl: 10.20.2.0:20002

➜  test-go ping6 5f6:bb70:c17:1c50:ff0f:b143:e764:3009
PING 5f6:bb70:c17:1c50:ff0f:b143:e764:3009(5f6:bb70:c17:1c50:ff0f:b143:e764:3009) 56 data bytes
64 bytes from 5f6:bb70:c17:1c50:ff0f:b143:e764:3009: icmp_seq=1 ttl=60 time=139 ms
64 bytes from 5f6:bb70:c17:1c50:ff0f:b143:e764:3009: icmp_seq=2 ttl=60 time=164 ms
64 bytes from 5f6:bb70:c17:1c50:ff0f:b143:e764:3009: icmp_seq=3 ttl=60 time=186 ms
64 bytes from 5f6:bb70:c17:1c50:ff0f:b143:e764:3009: icmp_seq=4 ttl=60 time=209 ms
64 bytes from 5f6:bb70:c17:1c50:ff0f:b143:e764:3009: icmp_seq=5 ttl=60 time=232 ms
64 bytes from 5f6:bb70:c17:1c50:ff0f:b143:e764:3009: icmp_seq=6 ttl=60 time=254 ms
64 bytes from 5f6:bb70:c17:1c50:ff0f:b143:e764:3009: icmp_seq=7 ttl=60 time=282 ms
64 bytes from 5f6:bb70:c17:1c50:ff0f:b143:e764:3009: icmp_seq=8 ttl=60 time=306 ms
64 bytes from 5f6:bb70:c17:1c50:ff0f:b143:e764:3009: icmp_seq=9 ttl=60 time=329 ms
64 bytes from 5f6:bb70:c17:1c50:ff0f:b143:e764:3009: icmp_seq=10 ttl=60 time=139 ms
64 bytes from 5f6:bb70:c17:1c50:ff0f:b143:e764:3009: icmp_seq=11 ttl=60 time=168 ms
64 bytes from 5f6:bb70:c17:1c50:ff0f:b143:e764:3009: icmp_seq=12 ttl=60 time=187 ms
64 bytes from 5f6:bb70:c17:1c50:ff0f:b143:e764:3009: icmp_seq=13 ttl=60 time=209 ms
64 bytes from 5f6:bb70:c17:1c50:ff0f:b143:e764:3009: icmp_seq=14 ttl=60 time=232 ms
64 bytes from 5f6:bb70:c17:1c50:ff0f:b143:e764:3009: icmp_seq=15 ttl=60 time=254 ms
64 bytes from 5f6:bb70:c17:1c50:ff0f:b143:e764:3009: icmp_seq=16 ttl=60 time=283 ms
64 bytes from 5f6:bb70:c17:1c50:ff0f:b143:e764:3009: icmp_seq=17 ttl=60 time=299 ms
64 bytes from 5f6:bb70:c17:1c50:ff0f:b143:e764:3009: icmp_seq=18 ttl=60 time=343 ms
64 bytes from 5f6:bb70:c17:1c50:ff0f:b143:e764:3009: icmp_seq=19 ttl=60 time=142 ms
^C
--- 5f6:bb70:c17:1c50:ff0f:b143:e764:3009 ping statistics ---
22 packets transmitted, 19 received, 13.6364% packet loss, time 21072ms
rtt min/avg/max/mdev = 138.611/229.235/342.975/63.662 ms

```
