### ISSUE TITLE
mass deployer: support delete

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-go#685]
### Is your feature request related to a problem? Please describe

mass deployer: support delete using a subcommand e.g tfrobot delete 

### Describe the solution you'd like

mass deployer: support delete using a subcommand e.g tfrobot delete

**Comment by Eslam-Nawara** [comment]
## Work Completed
- Added support for deployments cancelation of config file

### Verification
used this config file to deploy 5 vms 
```yaml
node_groups:
  - name: group_a
    nodes_count: 3 # amount of nodes to be found
    free_cpu: 2 # number of logical cores
    free_mru: 16384 # amount of memory in MB
    free_ssd: 100 # amount of ssd storage in GB
    free_hdd: 50 # amount of hdd storage in GB
    dedicated: false # are nodes dedicated
    public_ip4: true # should the nodes have free ip v4
    public_ip6: false # should the nodes have free ip v6
    certified: false # should the nodes be certified(if false the nodes could be certified of diyed) 
    region: "europe" # region could be the name of the continents the nodes are located in (africa, americas, antarctic, antarctic ocean, asia, europe, oceania, polar)
vms:
  - name: examplevm
    vms_count: 5 # amount of vms with the same configurations
    node_group: group_a # the name of the predefined group of nodes
    cpu: 1 # number of logical cores, min 1, max 32
    mem: 256 # amount of memory in MB, min 256 MB, max 256*1024 MB
    ssd: # list of ssd storage needed to be mounted to the vm
      - size: 15 # size in GB, min 15 GB
        mount_point: /mnt/ssd
    public_ip4: true 
    public_ip6: false
    flist: https://hub.grid.tf/tf-official-apps/base:latest.flist
    entry_point: /sbin/zinit init
    root_size: 0 # root size in GB, 0 for default root size, max 10TB
    ssh_key: example1 # the name of the predefined ssh key

ssh_keys: # map of ssh keys with key=name and value=the actual ssh key
  example1: ssh_key1
# mnemonic: example-mnemonic # mnemonic of the user
# network: dev # eg: main, test, qa, dev
mnemonic: ***
network: main
```

- Deployed vms:  
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/67752395/934a16f8-e500-4647-a25d-815eb452a581)

- Cancelation: 
```console
➜  mass-deployer git:(development-mass-deployer-continuation) ✗ ./bin/tfrobot cancel -c example/conf.yaml
12:08PM INF validating configuration file
12:08PM INF done validating configuration file
12:08PM DBG network: main
12:08PM DBG mnemonic: ***
12:08PM INF starting peer session=tf-190320 twin=10804
12:08PM INF canceling contracts for project group_a
12:09PM INF group_a canceled
➜  mass-deployer git:(development-mass-deployer-continuation) ✗
```
