### ISSUE TITLE
mass deployer: holochain doesn't return public ip address back

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-go#686]
### Is your feature request related to a problem? Please describe

mass deployer: holochain doesn't return public ip address back

```
node_groups:

  - name: holo_vm_group
    nodes_count: 1 # amount of nodes to be found
    free_cpu: 2 # number of logical cores
    free_mru: 2048 # amount of memory in MB
    free_ssd: 100 # amount of ssd storage in GB
    free_hdd: 50 # amount of hdd storage in GB
    dedicated: false # are nodes dedicated
    pubip4: true # should the nodes have free ip v4
    pubip6: true # should the nodes have free ip v6
    certified: false # should the nodes be certified(if false the nodes could be certified of diyed) 
    region: europe # region could be the name of the continents the nodes are located in (africa, americas, antarctic, antarctic ocean, asia, europe, oceania, polar)
vms:

  - name: holo_vm
    vms_count: 1 # amount of vms with the same configurations
    node_group: holo_vm_group # the name of the predefined group of nodes
    cpu: 2 # number of logical cores
    mem: 2048 # amount of memory in MB
    pubip4: true
    pubip6: true
    flist: https://hub.grid.tf/mariobassem1.3bot/threefolddev-holochain-latest.flist
    entry_point: /usr/local/bin/entrypoint.sh
    root_size: 0 # root size in GB
    ssh_key: my_key # the name of the predefined ssh key

ssh_keys: # map of ssh keys with key=name and value=the actual ssh key

  my_key: AAAAC3NzaC1lZDI1NTE5AAAAINd/1n/YAfz/xrWmlqAKmVB2FbJDzBkCJ5TDec1zGwOJ

mnemonic: XXX
network: main # eg: main, test, qa, dev
```

### Describe the solution you'd like

should be able to get the public ip back

**Comment by Eslam-Nawara** [comment]
- pubip4 was changed to public_ip4 see [example](https://github.com/threefoldtech/tfgrid-sdk-go/blob/0babd00e98ead92455aaa93035ea59320ed35306/mass-deployer/example/conf.yaml)
- both node_group and vms now use this format.

### Verification
config.yaml
```yaml
node_groups:
  - name: group_a
    nodes_count: 3 # amount of nodes to be found
    free_cpu: 2 # number of logical cores
    free_mru: 16384 # amount of memory in MB
    free_ssd: 100 # amount of ssd storage in GB
    free_hdd: 50 # amount of hdd storage in GB
    dedicated: false # are nodes dedicated
    public_ip4: true # should the nodes have free ip v4
    public_ip6: false # should the nodes have free ip v6
    certified: false # should the nodes be certified(if false the nodes could be certified of diyed) 
    region: "europe" # region could be the name of the continents the nodes are located in (africa, americas, antarctic, antarctic ocean, asia, europe, oceania, polar)
vms:
  - name: examplevm
    vms_count: 5 # amount of vms with the same configurations
    node_group: group_a # the name of the predefined group of nodes
    cpu: 1 # number of logical cores, min 1, max 32
    mem: 256 # amount of memory in MB, min 256 MB, max 256*1024 MB
    ssd: # list of ssd storage needed to be mounted to the vm
      - size: 15 # size in GB, min 15 GB
        mount_point: /mnt/ssd
    public_ip4: true 
    public_ip6: false
    flist: https://hub.grid.tf/tf-official-apps/base:latest.flist
    entry_point: /sbin/zinit init
    root_size: 0 # root size in GB, 0 for default root size, max 10TB
    ssh_key: example1 # the name of the predefined ssh key

ssh_keys: # map of ssh keys with key=name and value=the actual ssh key
  example1: ssh_key1

mnemonic: ***
network: main
```

output: 
```console
➜  mass-deployer git:(development-mass-deployer-continuation) ✗ ./bin/tfrobot deploy -c example/conf.yaml
11:59AM INF validating configuration file
11:59AM INF done validating configuration file
11:59AM DBG network: main
11:59AM DBG mnemonic: ***
11:59AM INF starting peer session=tf-179674 twin=10804
11:59AM INF running deployer for node group group_a
12:00PM INF done deploying node group group_a
12:00PM INF deployment took 49.160850282s
ok:
group_a:
name: examplevm2
publicip4: 83.231.240.17/25
publicip6: ""
yggip: ""
ip: 10.20.2.2
mounts:
    - diskname: examplevmdisk
      mountpoint: /mnt/ssd

name: examplevm1
publicip4: 83.231.240.18/25
publicip6: ""
yggip: ""
ip: 10.20.2.2
mounts:
    - diskname: examplevmdisk
      mountpoint: /mnt/ssd

name: examplevm0
publicip4: 195.192.213.16/24
publicip6: ""
yggip: ""
ip: 10.20.2.2
mounts:
    - diskname: examplevmdisk
      mountpoint: /mnt/ssd

name: examplevm4
publicip4: 83.231.240.19/25
publicip6: ""
yggip: ""
ip: 10.20.2.2
mounts:
    - diskname: examplevmdisk
      mountpoint: /mnt/ssd

name: examplevm3
publicip4: 195.192.213.17/24
publicip6: ""
yggip: ""
ip: 10.20.2.2
mounts:
    - diskname: examplevmdisk
      mountpoint: /mnt/ssd
➜  mass-deployer git:(development-mass-deployer-continuation) ✗
```
