### ISSUE TITLE
Update mass deployer validation to return more informative messages

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-go#711]
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/64129/b83cc0d9-7e14-4601-9223-ba83cd93a569)

I used this config 

```
node_groups:

  - name: holo_vm_group
    nodes_count: 1 # amount of nodes to be found
    free_cpu: 2 # number of logical cores
    free_mru: 2048 # amount of memory in MB
    free_ssd: 100 # amount of ssd storage in GB
    free_hdd: 50 # amount of hdd storage in GB
    dedicated: false # are nodes dedicated
    public_ip4: true # should the nodes have free ip v4
    public_ip6: true # should the nodes have free ip v6
    certified: false # should the nodes be certified(if false the nodes could be certified of diyed) 
    region: europe # region could be the name of the continents the nodes are located in (africa, americas, antarctic, antarctic ocean, asia, europe, oceania, polar)
vms:

  - name: holo_vm
    vms_count: 1 # amount of vms with the same configurations
    node_group: holo_vm_group # the name of the predefined group of nodes
    cpu: 2 # number of logical cores
    mem: 2048 # amount of memory in MB
    public_ip4: true
    public_ip6: true
    flist: https://hub.grid.tf/mariobassem1.3bot/threefolddev-holochain-latest.flist
    entry_point: /usr/local/bin/entrypoint.sh
    root_size: 0 # root size in GB
    ssh_key: my_key # the name of the predefined ssh key

ssh_keys: # map of ssh keys with key=name and value=the actual ssh key
  my_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCeq1MFCQOv3OCLO1HxdQl8V0CxAwt5AzdsNOL91wmHiG9ocgnq2yipv7qz+uCS0AdyOSzB9umyLcOZl2apnuyzSOd+2k6Cj9ipkgVx4nx4q5W1xt4MWIwKPfbfBA9gDMVpaGYpT6ZEv2ykFPnjG0obXzIjAaOsRthawuEF8bPZku1yi83SDtpU7I0pLOl3oifuwPpXTAVkK6GabSfbCJQWBDSYXXM20eRcAhIMmt79zo78FNItHmWpfPxPTWlYW02f7vVxTN/LUeRFoaNXXY+cuPxmcmXp912kW0vhK9IvWXqGAEuSycUOwync/yj+8f7dRU7upFGqd6bXUh67iMl7 ahmed@ahmedheaven"
  # my_key: AAAAC3NzaC1lZDI1NTE5AAAAINd/1n/YAfz/xrWmlqAKmVB2FbJDzBkCJ5TDec1zGwOJ

mnemonic: XXX
network: main # eg: main, test, qa, dev

```

I should be getting more clear response which wrong units are used where
