### ISSUE TITLE
mass-deployer: panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-go#712]
I change the units to be GB for mru

```
node_groups:

  - name: holo_vm_group
    nodes_count: 1 # amount of nodes to be found
    free_cpu: 2 # number of logical cores
    free_mru: 1 # amount of memory in MB
    free_ssd: 100 # amount of ssd storage in GB
    free_hdd: 50 # amount of hdd storage in GB
    dedicated: false # are nodes dedicated
    public_ip4: true # should the nodes have free ip v4
    public_ip6: true # should the nodes have free ip v6
    certified: false # should the nodes be certified(if false the nodes could be certified of diyed) 
    region: europe # region could be the name of the continents the nodes are located in (africa, americas, antarctic, antarctic ocean, asia, europe, oceania, polar)
vms:

  - name: holo_vm
    vms_count: 1 # amount of vms with the same configurations
    node_group: holo_vm_group # the name of the predefined group of nodes
    cpu: 2 # number of logical cores
    mem: 2 # amount of memory in MB
    public_ip4: true
    public_ip6: true
    flist: https://hub.grid.tf/mariobassem1.3bot/threefolddev-holochain-latest.flist
    entry_point: /usr/local/bin/entrypoint.sh
    root_size: 0 # root size in GB
    ssh_key: my_key # the name of the predefined ssh key

ssh_keys: # map of ssh keys with key=name and value=the actual ssh key
  my_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCeq1MFCQOv3OCLO1HxdQl8V0CxAwt5AzdsNOL91wmHiG9ocgnq2yipv7qz+uCS0AdyOSzB9umyLcOZl2apnuyzSOd+2k6Cj9ipkgVx4nx4q5W1xt4MWIwKPfbfBA9gDMVpaGYpT6ZEv2ykFPnjG0obXzIjAaOsRthawuEF8bPZku1yi83SDtpU7I0pLOl3oifuwPpXTAVkK6GabSfbCJQWBDSYXXM20eRcAhIMmt79zo78FNItHmWpfPxPTWlYW02f7vVxTN/LUeRFoaNXXY+cuPxmcmXp912kW0vhK9IvWXqGAEuSycUOwync/yj+8f7dRU7upFGqd6bXUh67iMl7 ahmed@ahmedheaven"
  # my_key: AAAAC3NzaC1lZDI1NTE5AAAAINd/1n/YAfz/xrWmlqAKmVB2FbJDzBkCJ5TDec1zGwOJ

mnemonic: XXX
network: main # eg: main, test, qa, dev

```

then this happened

```
➜  tfgrid-sdk-go_Linux_x86_64 ./tfrobot deploy -c my_holo_deployment.yaml -o out.yaml
9:57PM INF validating configuration file
9:57PM INF done validating configuration file
9:57PM DBG network: main
9:57PM DBG mnemonic: XXXX
9:57PM INF starting peer session=tf-2133666 twin=10466
9:57PM INF twin relay/public key didn't match, updating on chain ...
9:57PM INF running deployer for node group holo_vm_group
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/threefoldtech/tfgrid-sdk-go/mass-deployer/pkg/mass-deployer.buildDeployments({0xc0000c4780?, 0x1, 0x14d?}, {0xc0000131e0, 0xd}, {0xc00019ecd8, 0x1, 0xc00026d859?}, 0x7?)
	/home/runner/work/tfgrid-sdk-go/tfgrid-sdk-go/mass-deployer/pkg/mass-deployer/deployer.go:144 +0x205
github.com/threefoldtech/tfgrid-sdk-go/mass-deployer/pkg/mass-deployer.parseGroupVMs({0xc0001f05a0?, 0x1, 0x41?}, {0xc0000131e0, 0xd}, {0xc00019ecd8, 0x1, 0x1}, 0x13?)
	/home/runner/work/tfgrid-sdk-go/tfgrid-sdk-go/mass-deployer/pkg/mass-deployer/deployer.go:112 +0x2a7
github.com/threefoldtech/tfgrid-sdk-go/mass-deployer/pkg/mass-deployer.deployNodeGroup({0x28e2, {0xc0000343c0, 0x41}, {0xc6d050, 0xc0000ce1c0}, {0xac743f, 0x18}, {0xac3858, 0x13}, 0x6fc23ac00, ...}, ...)
	/home/runner/work/tfgrid-sdk-go/tfgrid-sdk-go/mass-deployer/pkg/mass-deployer/deployer.go:94 +0xec
github.com/threefoldtech/tfgrid-sdk-go/mass-deployer/pkg/mass-deployer.RunDeployer.func1({0xc69fe0?, 0x1088420?})
	/home/runner/work/tfgrid-sdk-go/tfgrid-sdk-go/mass-deployer/pkg/mass-deployer/deployer.go:45 +0x185
github.com/sethvargo/go-retry.Do({0xc69fe0, 0x1088420}, {0xc65940, 0xc0008d6660}, 0xc0005d96f8)
	/home/runner/go/pkg/mod/github.com/sethvargo/go-retry@v0.2.4/retry.go:60 +0x8a
github.com/threefoldtech/tfgrid-sdk-go/mass-deployer/pkg/mass-deployer.RunDeployer({{0xc00007e780, 0x1, 0x1}, {0xc0001f05a0, 0x1, 0x1}, 0xc0001c4d80, {0xc0000343c0, 0x41}, {0xc000013358, ...}, ...}, ...)
	/home/runner/work/tfgrid-sdk-go/tfgrid-sdk-go/mass-deployer/pkg/mass-deployer/deployer.go:40 +0x466
github.com/threefoldtech/tfgrid-sdk-go/mass-deployer/cmd.glob..func2(0xc0001be200?, {0xabc69c?, 0x4?, 0xabc6a0?})
	/home/runner/work/tfgrid-sdk-go/tfgrid-sdk-go/mass-deployer/cmd/deploy.go:41 +0x3f6
github.com/spf13/cobra.(*Command).execute(0x1051340, {0xc0000413c0, 0x4, 0x4})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xaa3
github.com/spf13/cobra.(*Command).ExecuteC(0x1051620)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/threefoldtech/tfgrid-sdk-go/mass-deployer/cmd.Execute()
	/home/runner/work/tfgrid-sdk-go/tfgrid-sdk-go/mass-deployer/cmd/root.go:18 +0x1a
main.main()
	/home/runner/work/tfgrid-sdk-go/tfgrid-sdk-go/mass-deployer/main.go:6 +0xf

```
