### ISSUE TITLE
🐞 [Bug] TFRobot: print more info about the VMs 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#723]
### What happened?

Add some more information about the VMs, like contract ID, node or farm ID, and maybe the resource or flist.
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/3432a974-5c9d-4961-bcbd-4b61647562c9)

### which network/s did you face the problem on?

Dev

### Relevant log output

```console
.
```

**Comment by rawdaGastan** [comment]
Added:

If you need more info tell me. I think those are enough

```yaml
 name: vms11
          networkname: vms11network
          networkname2: ""
          publicip4: ""
          publicip6: ""
          yggip: ""
          ip: 10.20.2.2
          mounts:
            - diskname: vms1disk
              mountpoint: /mnt/ssd/
          nodeid: 164
          contractid: 74987
```
