### ISSUE TITLE
Deployment Speed Test: Measure the time taken for deploying vms on a node group and vms on multiple node groups.

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#836]
I tried every group a few times, and it was always the same or a few seconds different.

- Deployment of 1 node group with 1 VM took about 20 seconds.
`INF Deployment took 18.759858258s`
- Deployment of 1 node group with 10 VMs took about 45 seconds.
`INF Deployment took 43.520713689s`
- Deployment of 1 node group with 100 VMs took about 7 minutes.
`INF Deployment took 6m37.168846966s`
- Deployment of 1 node group with 250 VMs took about 20 minutes.
`INF Deployment took 18m24.527114889s`

- Deployment of 2 node groups with 2 100-VM groups took about 3 minutes.
`INF Deployment took 3m47.063599418s`
- Deployment of 2 node groups with 2 100-VM groups took about 15 minutes.
`INF Deployment took 14m57.220318056s`

So as we add more groups, the numbers just keep doubling, as the deployment process is continuous, not parallel.
The only thing that could increase the time is failures and retries (which could be a lot less on the mainnet since the devnet doesn't have a lot of available resources).

**Comment by A-Harby** [comment]
> Resource Utilization During Deployment: Monitor CPU, memory, and network utilization during deployment.

The system resource monitor was giving a normal percentage through the whole deployment, except for two cases in which it had a spike.

Firstly, when it started to work connecting and validating the files.
Secondly, when the message `DBG Deploying 100 virtual machines, this may to take a while` was printed.

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/50c4560c-7c53-411f-b4a3-3aa3c3e8fbcc)

**Comment by A-Harby** [comment]
Node group
```
  - name: group_a
    nodes_count: 3
    free_cpu: 5
    free_mru: 85
    free_ssd: 10
    free_hdd: 10
```
VM group
```
  - name: examplevm
    vms_count: 10
    node_group: group_a
    cpu: 1
    mem: 1
    flist: 'https://hub.grid.tf/tf-official-apps/base:latest.flist'
    entry_point: '/sbin/zinit init'
    root_size: 0
    ssh_key: example1
    env_vars:
      user: user1
      pwd: 1234
```
