### ISSUE TITLE
tfrobot: Support deployments cancelation on Ctrl+c

### ISSUE THREAD

**Issue by Eslam-Nawara** [threefoldtech/tfgrid-sdk-go#838]
### Is your feature request related to a problem? Please describe

tfrobot stops deployment on Ctrl+c but don't cancel deployed vms

### Describe the solution you'd like

Cancelation on Ctrl+c should be added to clean up after not completed deployments

**Comment by Eslam-Nawara** [comment]
Work completed:
tried to run 4 vm groups on different node groups and send SIGTERM
```console
➜  tfrobot git:(development-cancel-deployments-on-SIGTERM) ✗ go run main.go deploy -c config.yaml
2:40PM INF starting peer session=tf-320046 twin=10804
2:40PM INF validating configuration file
2:40PM INF done validating configuration file
2:40PM INF Running deployment Node group=group_a
2:40PM INF Filter nodes Node group=group_a
2:40PM WRN Planetary and public IP options are false. Setting planetary IP to true vms group=example1vm
2:40PM INF Starting mass deployment Node group=group_a
2:41PM INF Retrying to deploy Deployment trial=2 Node group=group_a
2:41PM INF Filter nodes Node group=group_a
2:41PM INF Starting mass deployment Node group=group_a
2:41PM INF Done deploying Node group=group_a
2:41PM INF Running deployment Node group=group_b
2:41PM INF Filter nodes Node group=group_b
2:41PM WRN Planetary and public IP options are false. Setting planetary IP to true vms group=example2vm
2:41PM INF Starting mass deployment Node group=group_b
^C
2:41PM INF canceling contracts project name=group_b
2:42PM INF Running deployment Node group=group_c
2:42PM INF canceling contracts project name=group_c
2:42PM INF project is canceled project name=group_c
2:42PM INF Running deployment Node group=group_d
2:42PM INF canceling contracts project name=group_d
2:42PM INF project is canceled project name=group_d
2:42PM INF canceling contracts project name=group_a
2:42PM INF canceling contracts project name=group_b
2:42PM INF project is canceled project name=group_b
2:42PM INF canceling contracts project name=group_c
2:42PM INF project is canceled project name=group_c
2:42PM INF canceling contracts project name=group_d
2:42PM INF project is canceled project name=group_d
2:42PM FTL error="failed to run deployer, deployment was interrupted with signal SIGTERM"
exit status 1
➜  tfrobot git:(development-cancel-deployments-on-SIGTERM)

```

**Comment by A-Harby** [comment]
It didn't work with me; I deployed and stopped it, and it didn't cancel any of the deployed contracts.

```
node_groups:
  - name: group_a
    nodes_count: 3
    free_cpu: 5
    free_mru: 85
    free_ssd: 10
    free_hdd: 10
  - name: group_b
    nodes_count: 3
    free_cpu: 5
    free_mru: 85
    free_ssd: 10
    free_hdd: 10
  - name: group_c
    nodes_count: 3
    free_cpu: 5
    free_mru: 85
    free_ssd: 10
    free_hdd: 10
vms:
  - name: examplevm
    vms_count: 1
    node_group: group_a
    cpu: 1
    mem: 10
    flist: 'https://hub.grid.tf/tf-official-apps/base:latest.flist'
    entry_point: '/sbin/zinit init'
    root_size: 0
    ssd:
      - size: 15
        mount_point: '/mnt/ssd'
    ssh_key: example1
    env_vars:
      user: user1
      pwd: 1234
  - name: examplevm
    vms_count: 1
    node_group: group_b
    cpu: 1
    mem: 10
    flist: 'https://hub.grid.tf/tf-official-apps/base:latest.flist'
    entry_point: '/sbin/zinit init'
    root_size: 0
    ssd:
      - size: 15
        mount_point: '/mnt/ssd'
    ssh_key: example1
    env_vars:
      user: user1
      pwd: 1234
  - name: examplevm
    vms_count: 1
    node_group: group_c
    cpu: 1
    mem: 10
    flist: 'https://hub.grid.tf/tf-official-apps/base:latest.flist'
    entry_point: '/sbin/zinit init'
    root_size: 0
    ssd:
      - size: 15
        mount_point: '/mnt/ssd'
    ssh_key: example1
    env_vars:
      user: user1
      pwd: 1234
```
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/1e963d7c-fc3a-4abf-a5d5-2011a773a3d0)

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/1c394d62-0d52-489d-adff-ba27da8fb7d1)
